name: Sync to Internal Org Repo

on:
  push:
    branches: ['*']
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout external repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to internal org repository
        env:
          PAT: ${{ secrets.TARGET_REPO_PAT }}
        run: |
          git remote add target https://x-access-token:${PAT}@github.com/tiibntick-org/TiiBnTick-RelayPoint-Frontend.git
          git push --force target --all