name: Sync to Internal Org Repo

on:
  push:
    branches:
      - main # Change to master if your default branch is master

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout external repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags

      - name: Push changes to internal org repository
        run: |
          git remote add target https://x-access-token:${{ secrets.TARGET_REPO_PAT }}@github.com/tiibntick-org/TiiBnTick-RelayPoint-Frontend.git
          git push --force target main